language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep_history: true
  on:
    branch: master
